hh-village/FE

package.json, src/App.js, src/components/global/LoginBtn.jsx, src/components/global/SearchInput.jsx, src/pages/Redirect.jsx, src/shared/Router.js, yarn.lock
=> 카카오 소셜 로그인 구현 완료

package.json, src/components/RegistComponents/ImageBlock.jsx, src/components/RegistComponents/Map.jsx, src/components/RegistComponents/RegistStyled.js, src/hooks/useInput.js, src/index.js, src/pages/Redirect.jsx, src/pages/Regist.jsx, src/redux/config/configStore.js, src/redux/modules/Post.js, yarn.lock
- 위도/경도를 다시 지번으로 바꾸는 로직 서버랑 통신 대기중
- 추가적인 CSS 구성 디자이너 작업 후에 진행 예정
=> [feat] Waiting Reverse GeoCode

package.json, src/components/detail/ConsumerRegister.jsx, src/components/detail/RegisterReserve.jsx, src/components/detail/ReserveSelect.jsx, src/components/detail/detailStyle.js, src/pages/Detail.jsx, yarn.lock
- 달력 완성
- 옵션 onclick event 마저 완성하기
=>  예약시스템 통신제외 완성

src/components/detail/ConsumerRegister.jsx, src/pages/Detail.jsx
-예약 삭제완료
-예약 취소 구현 완료
- 위에 둘다 invalidate 구현까지 완료
=> [feat] 예약invalidate 구현완료

src/components/detail/ConsumerRegister.jsx, src/components/detail/RegisterReserve.jsx, src/pages/Detail.jsx, src/pages/Regist.jsx
-useQueryclien() 이용해서 unique한 QueryKey 사용 후 invalidate 문제해결
- 비동기 통신 오류를 isLoading 상태값을 이용해서 해결
=> [chore] invalidate 문제해결, isLoading문제 해결

src/pages/Home.jsx
=> [tempSave]메인페이지 개발 시작

public/index.html, src/components/global/HeaderNav.jsx, src/components/global/LogoutBtn.jsx, src/components/global/SearchInput.jsx, src/components/global/globalStyle.js, src/components/intro/DoneList.jsx, src/pages/Detail.jsx, src/pages/Home.jsx, src/pages/Intro.jsx, src/pages/MyPage.jsx, src/shared/Cookies.js
메인페이지 전체 조회 구현 및 기초 레이아웃 완료
인트로 페이지 거래 체결 내역 구현 완료, 무한 롤링으로 개선 예정
클라이언트 쿠키 삭제로 로그아웃 구현 완료
=> [tempSave]메인페이지 전체 조회 구현 완료, 인트로 페이지 거래 체결 내역 구현 중

package.json, src/components/detail/ConsumerRegister.jsx, src/components/global/globalStyle.js, src/pages/Chat.jsx, src/pages/Login.jsx, src/pages/Search.jsx
chore : 마이페이지 css수정 중, 찜 기능 연결 완료
=> chore : 마이페이지 css수정 중, 찜 기능 연결 완료

src/components/detail/ConsumerRegister.jsx, src/pages/Chat.jsx
- Websocket 통신 중 잔오류 해결
- 방 따라 다니는 오류 해결 중
=> [tempSave] 채팅 잔버그 수정중 테스트 겸 merge

src/components/global/globalStyle.js, src/pages/Home.jsx, src/pages/MyPage.jsx, src/pages/Search.jsx
tempSave : 메인페이지 기능 연결 및 CSS작업 중
=> tempSave : 메인페이지 기능 연결 및 CSS작업 중

src/components/detail/Calander.jsx, src/components/detail/ConsumerRegister.jsx, src/components/detail/RegisterReserve.jsx, src/components/detail/StatusBlock.jsx, src/components/detail/detailStyle.js, src/components/global/HeaderNav.jsx, src/components/global/LogoutBtn.jsx, src/pages/Login.jsx
- tempSave 에약 시스템 css 작업 중
- Regist 페이지 css 진행 예정
- 채팅 페이지 css 진행 예정
=> [tempSave] css 작업 도중 중간 merge

src/components/search/SearchCards.jsx, src/pages/Home.jsx, src/redux/modules/Search.js
=> chore : 메인페이지, 마이페이지 자잘한 수정

src/components/chat/chatStyle.js, src/components/global/HeaderNav.jsx, src/pages/Chat.jsx, src/pages/Login.jsx, src/pages/Regist.jsx
Bug1. 로그인 > 완료 > 뒤로가기 > 로그인 화면 진입 가능
Bug2. 메인화면 > 물품등록 클릭 > 화이트 아웃
Bug4. 메인페이지 > 채팅 버튼 클릭 > 진입되지 않음 (예외처리)
Bug5. 상세페이지 > 채팅하기 > 진입되지 않음(예외처리)
-> 모두 해결 완료!
=> [bugfix 1차 버그수정, 채팅, 비동기 오류 해결

public/index.html, src/App.js, src/pages/Login.jsx
=> chore : 중요 key env처리

src/pages/Chat.jsx
=> [bugfix] 채팅 글자 넘어가는거 버그 수정

src/components/detail/ConsumerRegister.jsx, src/pages/Login.jsx, src/pages/MyPage.jsx, src/pages/Regist.jsx
- useEffect 가드 설치 완료
- 예외처리 모두 완료...
=> [bugfix] 예외처리 모두 처리완료, useEffect 가드설치 완료

src/pages/MyPage.jsx
=> chore : 피드 받은 버그에서 자잘한 수정

src/pages/Detail.jsx
=> [bugfix] 스크롤 버그 오류 해결

package.json, src/components/home/DealList.jsx, src/components/home/VerticalCard.jsx, src/components/search/SearchCards.jsx, src/pages/Home.jsx, src/pages/Login.jsx, src/pages/MyPage.jsx, src/pages/Search.jsx, yarn.lock
feat : 검색페이지 no-offset 무한스크롤 구현
=> feat : 검색페이지 no-offset 무한스크롤 구현

src/components/global/SearchInput.jsx, src/components/mypage/UserCard.jsx, src/components/regist/Map.jsx, src/hooks/useGetDetail.js, src/hooks/useInput.js, src/pages/Chat.jsx, src/pages/Detail.jsx, src/pages/Login.jsx, src/pages/Regist.jsx, src/pages/Search.jsx
- location = ‘’ 
- 테스트 계정 여러개 
- 숫자 앞에 0 나오는거 
- 새로 대여된 물품 바꾸기
- 서치하고 안지우면 메인에서 검색을 해도 남아있다.
- maxlength  6자리
- 기존 값 가져오기 닉네임 
- 지도 무작위 요청 금지!
- 한번에 검색
=> [bugfix] 검색페이지 버그 수정, 예외처러, 테스트계등등

src/components/detail/ConsumerRegister.jsx, src/components/mypage/UserCard.jsx, src/pages/Detail.jsx
- 테스트 계정 수정 권한 제외
- 예약 등록시 alert 설정
=> [bugfix] 테스트계정 수정 권한 제외, 등록시 알림표시

.vscode/settings.json, src/components/global/SearchInput.jsx, src/components/mypage/UserCard.jsx, src/components/search/SearchCards.jsx, src/pages/Search.jsx
fix : 검색 기능 버그 수정, 마이페이지 닉네임 토큰 수정
=> fix : 검색 기능 버그 수정, 마이페이지 닉네임 토큰 수정

src/components/detail/Calander.jsx, src/components/detail/ConsumerRegister.jsx, src/components/detail/ImageSlider.jsx, src/components/detail/ModalSeller.jsx, src/components/detail/PostInfo.jsx, src/components/detail/RegisterReserve.jsx, src/components/detail/detailStyle.js, src/components/regist/ImageBlock.jsx, src/components/regist/RegistStyled.js, src/hooks/useUpdateDetail.js, src/pages/Detail.jsx, src/pages/Home.jsx, src/pages/Regist.jsx
- 상품등록시 multifile 부연설명 모달 추가
- 등록시 빈 값일 때 무엇이 빈값인지에 대한 오류메세지 추가
- 이미지 등록시 취소 누르면 원래 있던 이미지 날라가는 현상 정정 완료
- 지도 밖 구역 눌러도 모달창 닫히는 옵션 추가
- 날짜 선택시 end date 선택하지 않고 등록시 undefined 창 뜨는거 오류 수정 완료
- 로그인 하지 않으면 지도 모달창 open 아예 안되게 막아놓음
- 대여 버튼 네이밍 정정(등록하기 -> 대여하기)
- 날짜 예약시, 예약 현황까지 알려주는 alert창 구성,
- 첫번째 예약등록시에는 예약 이후 상황 안내 메세지 구성
- 채팅 메세지 잔잔한 오류 수정
=> [bugfix] 유저테스트 기반 정정사항 모두 수정완료

public/index.html, src/components/global/Footer.jsx, src/components/mypage/UserCard.jsx, src/components/search/SearchCards.jsx, src/pages/Home.jsx, src/shared/Router.js
=> chore : 자잘한 수정

public/index.html, src/components/detail/ImageSlider.jsx, src/components/global/SearchInput.jsx, src/components/home/HomeImgSlide.jsx, src/components/home/VerticalCard.jsx, src/components/search/SearchCards.jsx, src/hooks/useGetMyPageData.js, src/hooks/useUpdateDetail.js, src/pages/Detail.jsx, src/pages/Home.jsx, src/pages/Login.jsx, src/pages/Search.jsx, yarn.lock
=> chore : 발표 전 자잘한 수정

src/hooks/useUpdateDetail.js, src/pages/Login.jsx
=> fix : 게시글 수정 픽스 완료

src/pages/Detail.jsx
fix : 디테일 요청 속도 최적화를 위한 lazy loading 제거
=> fix : 디테일 요청 속도 최적화를 위한 lazy loading 제거
